string  target_tool                     # ToolState 상수. "none"이면 반납만
string  park_facing                     # UV 반납 자세 지정
---
nail_msgs/ResultBase base
nail_msgs/ToolState state
---
int32   step                            # 0=반납 1=랙이동 2=픽업 3=TCP 4=상태확정
float64 percent
