string session_id
# scan_corners: top_left, top_right, bottom_right, bottom_left 순서의 공중 Pose 4개
geometry_msgs/Pose[] scan_corners
geometry_msgs/Pose nail_reference
geometry_msgs/Pose[] dummy_references
geometry_msgs/Vector3 press_direction
string frame_id

float64 coarse_pitch_mm
float64 fine_pitch_mm
float64 boundary_band_mm
int32 fine_max_points

float64 air_offset_z_mm
float64 max_depth_mm
float64 probe_speed_mms
float64 comparison_margin_n
float64 max_force_n
float64 lateral_force_limit_n
int32 confirm_samples
float64 stiffness_depth_mm
float64 material_min_separation_n_per_mm
int32 reference_repeats
float64 point_timeout_s

bool manual_probe_tool_confirmed
---
nail_msgs/ResultBase base
nail_msgs/BoundaryMap map
---
string STAGE_COARSE = "COARSE"
string STAGE_FINE = "FINE"

string stage
nail_msgs/ProbeMeasurement last_measurement
int32 points_done
int32 points_total
int32 boundary_candidate_count
float64 percent
